### ISSUE TITLE
Line numbers not working as expected

### ISSUE THREAD

**Issue by jwade0** [uiwjs/react-textarea-code-editor#176]
Seems that the line numbers are added as a data attr correct with `rehypePrism`,  but there is no built in styling for the numbers. Am I missing something? I tried the example code in a codesandbox. Thanks!

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/5d111ce2-7232-41a7-9d08-797e0ba68329">

**Comment by Jakobud** [comment]
I also cannot get line numbers to work at all using the current example. I copy pasted the example 1:1 into this CodeSandbox just as @jwade0 did:

https://codesandbox.io/p/sandbox/https-github-com-uiwjs-react-textarea-code-editor-issues-151-forked-px5jfj?file=%2Fsrc%2FApp.js%3A24%2C1&workspaceId=e268bb81-c582-4f74-bdf5-2e00c927b2a4

![image](https://github.com/user-attachments/assets/6ad2ec83-2086-4150-86c2-d38a5decdeb0)

**Comment by lawlie8** [comment]
Any Update on This? Facing the Same Issue

**Comment by jacquesg** [comment]
You can try something like the following. I've adjusted the padding of the editor to 24px, and use a 14px font.

```scss
.code-line {
  position: relative;
}

.code-line::before {
  position: absolute;
  top: -8px;
  left: -20px;
  padding: 4px;
  content: attr(line);
  color: blue;
}
```
